Repository Midataur/mathsender, pull requests merged in 2020-08, with the labels that each got.

#26 refactored the autocorrect function
  main.py
Labels: Make it fast, Make it work

#35 add licence
  LICENSE
Labels: Make it good

#36 Change footer text
  faviconHQ.png
  mathsender design.sketch
  templates/base.html
Labels: Make it good

#37 Nicer copying
  static/main.css
  templates/base.html
Labels: Make it good

#40 fixed the latex bug
  main.py
  templates/studentquestion.html
Labels: Make it work
